version: "3.3"
services:
  spug:
    image: teddycode/punkos-spug:latest
    container_name: spug
    privileged: true
    restart: always
    volumes:
#      - /data/spug/backend/logs:/data/spug/spug_api/logs
      - ../../data/logs:/data/spug/spug_api/logs
#      - /data/spug/repos:/data/repos
      - ../../data/repos:/data/repos
    ports:
      # 如果80端口被占用可替换为其他端口，例如: - "8000:80"
      - "8000:80"
    environment:
      - SPUG_DOCKER_VERSION=v3.2.4