name: CI/CD for punkos_spug

on:
  push:
    branches:
      - punkos_main
  pull_request:
    branches:
      - punkos_main

jobs:
  backend:
    runs-on: self-hosted
    name: Backend CI/CD

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
        cache: 'pip' # caching pip dependencies

    - name: Upgrade pip
      run: python -m pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple/

    - name: Install backend dependencies
      run: |
        cd punkos_spug/spug_api
        pip install -U pip setuptools -i https://pypi.tuna.tsinghua.edu.cn/simple/
        pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/

    - name: Apply database migrations
      run: |
        cd punkos_spug/spug_api
        python manage.py updatedb

    - name: Create admin user
      run: |
        cd punkos_spug/spug_api
        python manage.py user add -u admin -p spug.cc -s -n 管理员

    - name: Start backend server
      run: |
        cd punkos_spug/spug_api
        nohup python manage.py runserver &

  frontend:
    runs-on: self-hosted
    name: Frontend CI/CD

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16.15.1'
        cache: 'npm'

    - name: Install frontend dependencies
      run: |
        cd punkos_spug/spug_web
        npm install

    - name: Build frontend
      run: |
        cd punkos_spug/spug_web
        npm run build
    
    - name: Deploy frontend
      run: |
        npm install -g serve
        serve -s punkos_spug/spug_web/build -l 3000
