name: CI/CD Pipeline

on:
  push:
    branches:
      - punkos_main
  pull_request:
    branches:
      - punkos_main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.15'

    - name: Install yarn
      run: |
        npm install -g yarn

    - name: Install dependencies and build frontend
      working-directory: ./spug_web
      run: |
        yarn 
        CI=false yarn build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_SECRET }}

    - name: Build and push Docker images
      run: | 
        docker build -f docs/docker/Dockerfile . -t teddycode/punkos-spug:latest 
        docker push teddycode/punkos-spug:latest

    - name: Deploy to server
      working-directory: ./docs/docker
      run: |
          docker-compose pull
          docker-compose up -d